//w01-project/contacts.rest
//Test project vocabulary and endpoints with sample rest operations

### Create a new contact
POST https://cse341-w02-project-1.onrender.com/contacts
Content-Type: application/json

{
    "contact_id": 11,
    "username": "tech_savvy",
    "email": "tech.savvy@example.com",
    "first_name": "Toby",
    "last_name": "Lewis",
    "birthday": "1990-01-06T00:00:00.000Z",
    "role": "Developer",
    "favorite_color": "black",
    "projects": [
        "Project A",
        "Project B"
    ],
    "active": true,
    "joined_date": "2023-11-01T19:00:00.000Z",
    "last_login_ip": "192.168.1.22"
}

### Get all contacts
GET https://cse341-w02-project-1.onrender.com/contacts

### Get contact by ID (contact-id)
GET https://cse341-w02-project-1.onrender.com/contacts/11

### Update contact by ID
PATCH https://cse341-w02-project-1.onrender.com/contacts/67daa208b432578cae3dd197
Content-Type: application/json

{
    "contact_id": "11",
    "username": "tech_savvy",
    "email": "tech.savvy@example.com",
    "first_name": "Toby2",
    "last_name": "Lewis"
}

### Update contact by ID using PUT
PUT https://cse341-w02-project-1.onrender.com/contacts/67daa208b432578cae3dd197
Content-Type: application/json

{
    "contact_id": "11",    
    "email": "tech.savvy@example.com",
    "first_name": "Toby4",
    "last_name": "Lewis"
}

### Delete contact by ID
DELETE https://cse341-w02-project-1.onrender.com/contacts/67daa208b432578cae3dd197

### Delete all contacts
DELETE https://cse341-w02-project-1.onrender.com/contacts

### Get all contacts with role "Developer"
GET https://cse341-w02-project-1.onrender.com/contacts/developer

